name: dff
channels:
  - conda-forge
  - defaults
dependencies:
  - wget
  - cmake
  - zip
  - unzip
  - python
  - pip
  - pip:
      - mergin-client
      - bcdata==0.7.6
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5432
  PGDATABASE: newgraph
  DATABASE_URL: postgresql://postgres@localhost:5432/bcfishpass
  MERGIN_USERNAME: newgraph_airvine
