name: dff
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5432
  PGDATABASE: newgraph
  DATABASE_URL: postgresql://postgres@localhost:5432/bcfishpass
  MERGIN_USERNAME: newgraph_airvine
  # below is untested
  SQLite3_ROOT: /opt/homebrew/Cellar/sqlite/3.40.1/
channels:
  - conda-forge
  - defaults
dependencies:
  - wget
  - zip
  - unzip
  - python
  #- sqlite
  - pip
  - pip:
      - mergin-client
      - bcdata==0.7.6


